- name: Aplica lineamientos de cumplimiento, especificos y generales
  hosts: all
  become: true
  tasks:
    - name: Reglas previas a estándar CIS y calendarización
      ansible.builtin.include_tasks:
        file: tasks/tareas-previas.yml

    - name: Resuelve cumplimiento con el estándar CIS Benchmark
      ansible.builtin.include_role:
        name: dsglaser.cis_security.cis_security

    - name: Remediaciones correspondientes a Q1 2024
      ansible.builtin.include_tasks:
        file: tasks/2024-Q1.yml
