- name: Aplica lineamientos de seguridad
  hosts: all
  become: true
  tasks:
    - name: Reglas previas a ningun reporte de seguridad ni estándar
      ansible.builtin.include_tasks:
        file: tasks/tareas-previas.yml

    - name: Hardening estándar antes de ninguna remediación de reportes
      ansible.builtin.include_tasks:
        file: tasks/hardening-inicial.yml

    - name: Remediaciones correspondientes a Q1 2024
      ansible.builtin.include_tasks:
        file: tasks/2024-Q1.yml
        
    - name: Remediaciones correspondientes a Q2 2024
      ansible.builtin.include_tasks:
        file: tasks/2024-Q2.yml
