- name: Aplica lineamientos de cumplimiento, especificos y generales
  hosts: all
  become: true
  tasks:
    - name: Reglas previas a estándar CIS y calendarización
      ansible.builtin.include_tasks:
        file: tareas-previas.yml

    - name: Resuelve cumplimiento con el estándar CIS Benchmark
      ansible.builtin.include_role:
        name: dsglaser.cis_security.cis_security
      tags:
        - never

    - name: Remediaciones correspondientes a Q1 2024
      ansible.builtin.include_tasks:
        file: 2024-Q1.yml
