---
# week16
- name: Hallar archivos huérfanos y obligar resolución manual
  ansible.builtin.command:
    cmd: >-
      find /bin /boot /etc /home /lib /lib64 /opt /root /sbin /srv /tmp /usr /var 
      -nouser -o -nogroup
  failed_when: false
  register: orphaned_files

- name: Imprimir archivos a evaluar si existen
  ansible.builtin.debug:
    msg: "{{ orphaned_file.stdout }}"
  when: orphaned_files.rc == 0
  
- name: Fallar el host si existen archivos huérfanos
  ansible.builtin.fail:
    fail_msg: "Se hallaron archivos huérfanos, corregir manualmente"
  when: orphaned_files.rc == 0
...
